name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - run: git pull
      - run: composer install
      - run: php artisan migrate:fresh --seed
      - run: php artisan passport:client --personal
      - run: npm install


